#!/bin/bash
export TERM=screen-256color
source ~/.fzf.bash
cd $HOME


# WHICH OS?
case $( uname -s ) in
Linux)
    OS="LINUX"
    ;;
Darwin)
    OS="MAC"
    ;;
esac

# STARTX
if [ $OS == LINUX ] && [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ] && [ -z "$SSH_CONNECTION" ]; then

    # window manager
    [[ -z $DISPLAY && XDG_VTNR -eq 1 ]] && exec startx && xbindkeys
fi

# DIR PATHS
export DROPBOX="$HOME/Dropbox"
export PROJECTS="$DROPBOX/proj"
export DOTFILES="$PROJECTS/dotfiles"
export SCRIPTS="$DOTFILES/scripts"

# DIR SHORTCUTS
alias down="cd ~/Downloads";
alias dotfiles="cd $DOTFILES";
alias p="cd $PROJECTS";
alias scripts="cd $SCRIPTS"


# GIT ALIASES
alias gitlog="git log --graph \
    --abbrev-commit \
    --decorate \
    --date=relative \
    --format=format:'%C(bold blue)%h%C(reset) \
    - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' \
    --all"

# EXECUTIONAL SHORTCUTS
alias ls='ls -lh --group-directories-first --color'
alias la='ls -lha --color'
alias search='apt-cache search'
alias update='sudo apt-get update'
alias remove='sudo apt-get remove'
alias purge='sudo apt-get purge'
alias vimrc="vim $HOME/.vimrc";
alias bashrc="vim $HOME/.bash_profile && source $HOME/.bash_profile";
alias todo="vim $DROPBOX/TODO";

# ENVIRONMENTAL SETTINGS
export PATH=$PATH:$PROJECTS/dotfiles/scripts:/usr/local/src/zapcc/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/src/zapcc/lib
export VISUAL=vim
export EDITOR=vim

# SHELL SETTINGS
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}
PS1='[\w]\[\033[1;35m\]$(parse_git_branch)\[\033[0m\] > '
export HISTSIZE=1000000
export HISTFILESIZE=1000000000
if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi
stty -ixon  # disable ctrl-s (software flow control)

# # START TMUX ON BASH STARTUP
if [ $OS == "LINUX" ]; then
    if which tmux 2>&1 >/dev/null; then  # check if tmux is installed
        #if tmux ls 2>&1 >/dev/null; then  # check if tmux already has sessions
        #    [[ -z "$TMUX" ]] && exec tmux attach
        #else
            [[ -z "$TMUX" ]] && exec tmux -2 -f ~/.tmux.conf
        #fi
    fi
fi

alias todos='grep --exclude-dir=.git -rEI "TODO|FIXME" . 2>/dev/null'
export CXX=clang++
export ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-5.0/bin/llvm-symbolizer
export MSAN_SYMBOLIZER_PATH=/usr/lib/llvm-5.0/bin/llvm-symbolizer
export ASAN_OPTIONS=symbolize=1
export MSAN_OPTIONS=symbolize=1
eval $(thefuck --alias)


